### PR TITLE
Fix invalid timezone identifier bug

### LINKED ISSUE #87: Fails on bad timezone
I am working with a server that returns:

```
BEGIN:VTIMEZONE
TZID:Central Standard Time
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETFROM:-0500
TZOFFSETTO:-0600
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=1SU;BYMONTH=11
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:-0600
TZOFFSETTO:-0500
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=2SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
```

`TZID:Central Standard Time` is not a valid timezone identifier so the code fails on [`ICal.php:459`](https://github.com/u01jmg3/ics-parser/blob/4032ae36dc6a6cb0c858ec40363c6bbeb68ac565/src/ICal/ICal.php#L459).

### PR DESCRIPTION
**Pull request by ohryan**
Fixes #87 - fails on bad timezone

### CODE REVIEW

**Comment by u01jmg3** [comment]
Thanks for the PR.

Thinking about the logic behind this, would it not be better to check if the timezone is a valid one rather than defaulting to `$this->calendarTimeZone()`?

e.g.

```php
function isValidTimezoneId($tzid){
    $valid = array();
    $tza = timezone_abbreviations_list();
    foreach ($tza as $zone)
        foreach ($zone as $item)
            $valid[$item['timezone_id']] = true;
    unset($valid['']);
    return !!$valid[$tzid];
}
```

**Comment by ohryan** [comment]
My PR was narrowly focused on a specific bug I came across. 

I think your solution is a little more thorough.

**Comment by u01jmg3** [comment]
Happy to accept a modified PR or I can make the changes?

**Comment by ohryan** [comment]
I haven't had time to update my PR. If you're in a hurry feel free to make the change :)

**Comment by u01jmg3** [comment]
- Looking at the code further [this scenario is covered](https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/ICal.php#L1127-L1130)?
- Are you using `dev-master`?

**Comment by u01jmg3** [comment]
Closing as no activity and I believe the described scenario is covered. Happy to re-open if it is still a problem

**Pull request closed without merging**
