### PR TITLE
Add function to retrieve events from an interval string

### PR DESCRIPTION
**Pull request by grimmlink**
Following http://php.net/manual/fr/dateinterval.createfromdatestring.php 
Add the possibility to retrieve events from a string interval.

### CODE REVIEW

**Comment by u01jmg3** [comment]
Thanks for this

- Can you update the API section in the [README](https://github.com/u01jmg3/ics-parser#api)?
- Can you an add [example](https://github.com/u01jmg3/ics-parser/blob/master/examples/index.php#L33) similar to `eventsFromRange()`?

**Comment by grimmlink** [comment]
I made the patch directly in github, so it can't be myeditor, and i can't remove the line, kinda weird...

**Comment by grimmlink** [comment]
Regarding the new line, it seems there isn't and the diff line is just a notice
http://stackoverflow.com/questions/5813311/no-newline-at-end-of-file
http://stackoverflow.com/questions/9921927/php-is-there-a-reason-to-put-a-newline-at-the-end-of-file

**Comment by grimmlink** [comment]
I guess it fixes #57

**Pull request merged**
