### PR TITLE
Rename documented field lastmodified to last_modified as generated 

### PR DESCRIPTION
**Pull request by frantzmiccoli**
I have added a test, not sure it is relevant though.

### CODE REVIEW

**Comment by u01jmg3** [comment]
Thanks for the contribution.

What issue does this solve?

**Comment by frantzmiccoli** [comment]
The test is basically useless.

`lastmodified` was the declared field in the class (so in all autocompletion systems), but the parsed data is put in `last_modified`. It is just fixing this.

**Comment by u01jmg3** [comment]
> _but the parsed data is put in `last_modified`_

Sorry, whereabouts in the code?

**Comment by frantzmiccoli** [comment]
Around here: https://github.com/u01jmg3/ics-parser/pull/250/files#diff-cad15d971a6236da40446ed68aebcf31L126

**Comment by u01jmg3** [comment]
Closing for now as this has not been reported by anyone else.

Happy to re-open if necessary.

**Pull request closed without merging**
