### PR TITLE
Take into account changed recurrence instances

### LINKED ISSUE #55: Parsing recurring events doesn't account for event that has a changed DTSTART and/or DTEND listed in the file.
I have a recurring event on an ICAL file I pull from Google Apps. We recently had to modify the time of one instance of the recurring events. The modified event came up in the list at the proper new time, but the parser still generated and returned the event at the original time as well. It looks like events would be parsed for the UID of the recurring event and find out if for that RECURRENCE-ID the event differs from the RRULE setting for DTSTART and/or DTEND, and if so replace that particular event in the array generated from the RRULEs.

The events are in question are listed, with some redactions. There should be enough to replicate the issue.

Recurring event rule:

```
BEGIN:VEVENT
DTSTART;TZID=America/Chicago:20160406T103000
DTEND;TZID=America/Chicago:20160406T110000
RRULE:FREQ=WEEKLY;BYDAY=WE
DTSTAMP:20160426T220705Z
UID:UID@google.com
CREATED:20160406T175048Z
LAST-MODIFIED:20160406T210132Z
LOCATION:LOCATION
SEQUENCE:1
STATUS:CONFIRMED
SUMMARY:MEETING
TRANSP:OPAQUE
END:VEVENT
```

And a modified instance of the recurring event:

```
BEGIN:VEVENT
DTSTART;TZID=America/Chicago:20160427T130000
DTEND;TZID=America/Chicago:20160427T133000
DTSTAMP:20160426T220705Z
UID:UID@google.com
RECURRENCE-ID;TZID=America/Chicago:20160427T103000
CREATED:20160406T175048Z
LAST-MODIFIED:20160425T184416Z
LOCATION:LOCATION
SEQUENCE:2
STATUS:CONFIRMED
SUMMARY:MEETING
TRANSP:OPAQUE
END:VEVENT
```

### PR DESCRIPTION
**Pull request by s0600204**
By making a list of them and referring to said list when applicable.

Should fix #55

### CODE REVIEW

**Comment by u01jmg3** [comment]
Still getting 2 entries appear for `20160427` when I use the example and modify `MyCal.ics` to use the above iCal snippet. Should this happen?

**Comment by s0600204** [comment]
I am... unable to duplicate.

Adding the events of the above snippet into `MyCal.ics` of the example, I only get one entry with that datetime- http://s06eye.co.uk/ics-parser/test_issue81/ ([MyCal.ics](http://s06eye.co.uk/ics-parser/test_issue81/MyCal.ics))

**Comment by u01jmg3** [comment]
This is odd. Testing with just the code in this PR using your copy of MyCal.ics above, I get 157 events from 150. Looking at your web page link `test_issue81` I can see you get 150 as you should.

Is there definitely no code you have on your side missing from the PR? I can see you have the 'Calendar's Timezone' appearing at the top of the example page which isn't in this PR. Just trying to troubleshoot.

I have also created a branch with the exact code I am testing with - do you get 157 events with `20160427` repeated twice as I do?

**Comment by s0600204** [comment]
Using your branch ([link](http://s06eye.co.uk/ics-parser/test_issue81_2)), I get a count of 150 events at the top of the example page. I also get the `20160427` event appearing twice - once in the "Events March through April" section, and once in the "All Events" section - with both appearances being identical.

The only change I made is that I don't use `Composer` so I include `ICal` and `EventObject` files directly. Can't think why that would make a difference.

**Comment by u01jmg3** [comment]
> _I also get the 20160427 event appearing twice - once in the "Events March through April" section, and once in the "All Events" section - with both appearances being identical._

Ah, I think my interpretation is incorrect and things are working as they should.

--

Although the top of the page says 150 events, it doesn't take into account the 7 sub events generated from the range function.

Happy to merge and thanks for your time.

**Pull request merged**
