### PR TITLE
Check if timezones are valid. If not, set a default timezone

### LINKED ISSUE #75: Check if timezones are valid
Timezones detected into ICS files have to be checked to avoid PHP errors.
Some ICS files return something like `TZID:GMT+02.000/+03.000` which is not a PHP timezone format and this might generate errors.

I offer an enhancement that allow the user to define a default timezone which will be used if a wrong timezone is detected with the php function `timezone_identifiers_list`.

### PR DESCRIPTION
**Pull request by jeromecombes**
Hi,

I added some timezone checks.
See issue #75 .

I tried this update into my project before you to switch to composer installation.
Then, I adapted this changes to the composer installation from your latest commit, but I'm not enable to install ics-parser with composer into my own project (maybe you can help me). So please, do some tests.

Best,
Jérôme

### CODE REVIEW

**Comment by u01jmg3** [comment]
Thanks for this - when I have some time I will check this out

**Comment by s0600204** [comment]
Jérôme, have you considered using php's `date_default_timezone_get` function to get a default timezone?

Chances are that anyone using the `ics-parser` may be doing other date/time manipulation in their code, so they'll have already set a default timezone within php. And in the case they haven't, that function will return "UTC".

Also, what happens if the `$timeZone` argument passed to `__construct` is not a valid timezone?

**Comment by jeromecombes** [comment]
You are right, using the date_default_timezone_get function is really better. I didn't think about it.

Therefore we just have to keep changes into the functions iCalDateWithTimeZone and calendarTimeZone and to adapt them with date_default_timezone_get

**Comment by jeromecombes** [comment]
Hi,
As @s0600204 suggested, I updated Ical.php to use the date_default_timezone_get function to define the default timezone. See 457f445
It works fine in my project.

**Comment by u01jmg3** [comment]
Thanks for the PR - closing as I want to clean it up but the premise behind your code I shall add to the library.

**Pull request closed without merging**
