### PR TITLE
Support Mac/Linux line endings

### PR DESCRIPTION
**Pull request by dxdc**
Fixes https://github.com/u01jmg3/ics-parser/issues/124

### CODE REVIEW

**Comment by dxdc** [comment]
Perhaps the line should actually read:

```php
$string = str_replace(array("\n ", "\r\n ", "\r\n\t", "\n\t"), '', $string);
```

**Comment by u01jmg3** [comment]
This goes slightly against the spec for iCalendar (but prefer to have Mac/Linux compatibility):

> https://icalendar.org/iCalendar-RFC-5545/3-1-content-lines.html
>
> _The iCalendar object is organized into individual lines of text, called content lines. Content lines are delimited by a line break, which is a **CRLF** sequence (**CR** character followed by **LF** character)._

(Relates to #111)

**Comment by u01jmg3** [comment]
Yes please update

**Comment by dxdc** [comment]
There is likely a better way to deal with this (`PHP_EOL`), but you can review my latest commit.

**Comment by u01jmg3** [comment]
I will ponder but this will suffice for now - thanks

**Pull request merged**
