### PR TITLE
Cleanup code handling timezones when converting icalDate to PHP's DateTime

### PR DESCRIPTION
**Pull request by s0600204**
There are quite a few things currently wrong with this method:

- If a date is pre-1970, then a timezone *is* applied - so long as it's IANA (or converted Microsoft): support for CLDR timezones was never added into this logic path.

- If a date is pre-1970, the branch of code ignores the work done by the earlier `preg_match`, and acquires the timezone through string manipulation instead.

- If neither `$forceUtc` or `$forceTimezone` are true (i.e. the default state) then the timezone attached to a date is not applied to the date.

- If `$forceUtc` is `true`, but `$forceTimezone` is `false`, then all dates in a calendar are assumed to be UTC.

- If `$forceTimezone` is `true`, then the value of `$forceUtc` is functionally ignored.
  - This is also the only logic code path that a post-1969 date actually has its timezone applied.

- In all but two calls to this method, both `$forceTimezone` and `$forceUTC` are passed as `true` (contrary to their default value of `false`).
  - The two exceptions to this are the `dtstart` and `dtend` of the first date of a Monthly recurrence rule - meaning that the first date of said rule will have no timezone applied (unless pre-1970), whilst subsequent dates generated from the rule will.

- The provided changeset resolves all of that, and is a cleaner and saner approach to conversion.

### CODE REVIEW

**Comment by u01jmg3** [comment]
Immediately getting an exception:

```
Exception: DateTime::__construct(): Failed to parse time string (20171032T000000) at position 7 (2): Unexpected character
```

**Comment by u01jmg3** [comment]
I'm now getting:

```
Exception: Invalid iCal date format. in ics-parser\src\ICal\ICal.php:1035
```

Can you try testing with ['ICal.ics'](https://github.com/u01jmg3/ics-parser/blob/master/examples/ICal.ics)?

**Comment by u01jmg3** [comment]
@s0600204: thanks for being so quick with these fixes.

Reading your latest commit message:

> _Unfortunately, this means that CLDR timezone identifiers, (e.g. `Europe/Berlin`) also now have quotes around them and so do not get recognised as a valid timezone_

Can you see a way around this?

**Comment by s0600204** [comment]
The new method could, in theory, be used on all param-texts (as the iCal specification calls them) not just TZIDs, but applying it to all is beyond the intended scope of this pull request.

(And I meant `IANA` timezone identifiers, as `CLDR` identifiers are the ones that typically have a `:` in...)

**Comment by u01jmg3** [comment]
`composer test` has 3 failures

**Pull request merged**
